### ISSUE TITLE
AutoSaving日本語化

### ISSUE THREAD

**Issue by ArieSyVanish** [snake0623/SNAKENetWork-issue#10]
(青)Server>>(赤)AutoSaving

(青)Server>>(赤)AutoSave Complete

日本語化↓↓

(青)サーバー>>(赤)オートセーブをしています。
(青)サーバー>>(赤)オートセーブが完了しました。

**Comment by snake0623** [comment]
マルチバイト文字に置き換えると後々問題発生時に非常に大変というのと、特に置き換えなくても問題がないため、保留
